### ISSUE TITLE
Add your contributions to scores.yml (Everyone)

### ISSUE THREAD

**Issue by VamsiSangam** [fossiiita/opencode2017#128]
Add all your contributions so far to [scores.yml](https://github.com/fossiiita/opencodecollab/blob/master/_data/scores.yml). This must be done by everyone. Your contributions should be added under your github username in the following format -

```
- github: your_username
  contributions:
    - name: short_title_for_contribution
      link: url_to_contribution_as_proof
      score: 10
    - name: Added profile to students
      link: https://github.com/fossiiita/opencodecollab/pull/7
      score: 30
  total: 40
```

The ```total``` must be the total points gained by all the contributions and each contribution's score must also be mentioned in the given format. Add all your contributions correctly so that your name can rule the leaderboard! 😄 

For future contributions, you need to submit a quick PR to update your details in ```scores.yml```
